# Use Ubuntu 14.04.4 LTS to get clang-3.5
sudo: required
dist: trusty

language: cpp

compiler:
  - clang

before_script:
  - make -C ./emscripten/ SubModules
  - mkdir build
  - cd build
  - cmake ..

script: make
